spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: '${custom_local.db.driver-class-name}'
    url: '${custom_local.db.url}'
    username: '${custom_local.db.username}'
    password: '${custom_local.db.password}'
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${custom_local.oauth2.naver.client-id}
            client-secret: ${custom_local.oauth2.naver.secret}
            redirect-uri: ${custom_local.oauth2.naver.redirect-url}
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response