server:
  port: 8080

spring:
  application:
    name: igeodaeyeo

  profiles:
    active: dev
    include: secret

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: '${custom.db.url}'
    username: '${custom.db.username}'
    password: '${custom.db.password}'

  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
