server:
  port: 8080

spring:
  application:
    name: igeodaeyeo

  profiles:
    active: dev
    include: secret

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true