server:
  port: 8080

spring:
  application:
    name: igeodaeyeo

  profiles:
    active: dev
    include: secret

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true

  jwt:
    secret-key: ${custom_local.jwt.secret-key}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${custom_local.oauth2.naver.client-id}
            client-secret: ${custom_local.oauth2.naver.secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - nickname
          kakao:
            client-id: ${custom_local.oauth2.kakao.client-id}
            client-secret: ${custom_local.oauth2.kakao.secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post  # kakao의 인증 토큰 발급 메서드: post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명
